server:
  port: 3306

  spring:
    profiles:
      active: @spring.profiles.active@

app:
datasource:
  jdbc-url:jdbc: jdbc:mysql://dizzy-database.cunt841zgwhi.eu-central-1.rds.amazonaws.com:3306/demo_account
  username: dizzyadmin
  password: dizzyadmin
  pool-size: 30